### ISSUE TITLE
mkpasswd: it seems it is not possible to pass a salt when using yescrypt method

### ISSUE THREAD

**Issue by cquike** [rfc1036/whois#102]
I have tried to pass a salt to mkpasswd using the yescrypt method:
```
$ mkpasswd -m yescrypt --salt=1234567890123456789012 MYPASSWD
Wrong salt length: 22 bytes when 0 expected.
```
It doesn't seem to like any size of the salt and it always uses a random one. How can one pass the salt for yescrypt?

**Comment by rfc1036** [comment]
Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003151 .
