### ISSUE TITLE
Class B 150.230.0.0 gives wrong answer

### ISSUE THREAD

**Issue by verne-work** [rfc1036/whois#110]
The Class B space aka /16 of 150.230.0.0 with a generic 

`whois 150.230.0.0 `

gives outdated results, while a directed lookup with 

`whois -h whois.arin.net 150.230.0.0`

 comes back with the correct answer of Oracle Corp,

I see the Class A 150.0.0.0 is in your ip_del_list   .... should 150.230.0.0 be added to ip_del_recovered list ?

**Comment by rfc1036** [comment]
No, because the number of networks transferred among RIRs is unbounded. If you need to always get an answer on the first request then you may use `whois -I`, but even IANA does not get this prefix right (I do not know why).
