### ISSUE TITLE
Add .pk WHOIS server whois.pknic.net.pk

### ISSUE THREAD

**Issue by ashar9** [rfc1036/whois#114]
Reference IANA ccTLD Database:  https://www.iana.org/domains/root/db/pk.html

Add whois server for .pk in file tld_serv_list (instead of WEB URL): 

.pk	whois.pknic.net.pk

Can be seen at:
https://github.com/ashar9/rfc1036-whois/blob/next/tld_serv_list

**Comment by rfc1036** [comment]
Merged.
