### ISSUE TITLE
Wrong whois server for 154.6.204.0/22

### ISSUE THREAD

**Issue by VibeGAMESNL** [rfc1036/whois#127]
The program is "guessing" the wrong whois server to lookup 154.6.204.0/22.
It tries to use AfriNIC but its managed by ARIN and also reporting `The WHOIS is temporary unable to query ARIN for the requested resource. Please try again later`

># whois --version
>Version 5.5.13.
>
>Report bugs to <md+whois@linux.it>.
>root@SGP-H21-NEW:~# whois  154.6.207.5
>% This is the AfriNIC Whois server.
>% The AFRINIC whois database is subject to  the following terms of Use. See https://afrinic.net/whois/terms
>
>% Note: this output has been filtered.
>%       To receive output for a database update, use the "-B" flag.
>
>% The WHOIS is temporary unable to query ARIN for the requested resource. Please try again later.

**Comment by rfc1036** [comment]
Tough luck: at this point it is not practical to chase every inter-RIR transfer. If always getting automatically an answer is important to you then you should use `whois -I`.

**Comment by VibeGAMESNL** [comment]
In this case a third party that is not willing to cooperate, is using this tool for their license check. Due to lookup issues for this IP this check fails so I was hoping you would be able to do something on your side.

>whois -I 154.6.204.0
>refer:        whois.afrinic.net

>inetnum:      154.0.0.0 - 154.255.255.255
>organisation: Administered by AFRINIC
>status:       LEGACY
>
>whois:        whois.afrinic.net
>
>changed:      1993-05
>source:       IANA

>% This is the AfriNIC Whois server.
>% The AFRINIC whois database is subject to  the following terms of Use. See https://afrinic.net/whois/terms

>% Note: this output has been filtered.
>%       To receive output for a database update, use the "-B" flag.

>% The WHOIS is temporary unable to query ARIN for the requested resource. Please try again later.

**Comment by rfc1036** [comment]
Sorry, I cannot help if somebody is using the tool wrong.
I want to be extremely clear on this: nowadays there is a huge number of networks which have been transferred to a different RIR and it is not plausible to teach the client about all of them.
