### ISSUE TITLE
nic.ch queries issue

### ISSUE THREAD

**Issue by dragonofmercy** [rfc1036/whois#145]
Since version 5.5.13 nic.ch queries not work anymore.  
_Requests of this client are not permitted. Please use https://www.nic.ch/whois/ for queries._

Working fine with version 5.5.1

**Comment by pemensik** [comment]
Tested 5.5.1 and 5.3.2, no difference. The same with jwhois. I think they just require captcha check, so this whois can be disabled.

**Comment by rfc1036** [comment]
Actually the port 43 service still works from (at least) swiss IPs, so for the time being I will leave it as is.
