### ISSUE TITLE
mkspasswd scrypt method fails when specifying number of iterations

### ISSUE THREAD

**Issue by Krasauskas** [rfc1036/whois#148]
```
mkpasswd -m scrypt -R 16384
crypt_gensalt: Invalid argument
```

```
# mkpasswd --version
mkpasswd 5.5.13
```

Ubuntu 22.04

**Comment by rfc1036** [comment]
Looks like you have jumped to conclusions: it fails when you specify an _invalid_ number of iterations. The valid parameters for all algorithms are documented in crypt(5).

E.g.:

`echo foo | mkpasswd -s -m scrypt -R 11`
