### ISSUE TITLE
5.5.19 doesn't build with clang

### ISSUE THREAD

**Issue by nekopsykose** [rfc1036/whois#155]
```
./utils.h:62:7: error: 'malloc' attribute takes no arguments
void *MALLOC_FREE NONNULL do_nofail(void *ptr, const char *file, const int line)
      ^
./utils.h:20:37: note: expanded from macro 'MALLOC_FREE'
# define MALLOC_FREE __attribute__((malloc(free)))
                                    ^
1 error generated.
```

this is because clang doesn't implement the `malloc (deallocator)` attribute (ref https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html), just `malloc`. this was added in https://github.com/rfc1036/whois/commit/f01f8d405ba6b67e7648792e2e6a70ce71fb8ea8 . ref for llvm: https://github.com/llvm/llvm-project/issues/51607 https://github.com/llvm/llvm-project/issues/53152

**Comment by rfc1036** [comment]
Please send a patch.

**Comment by marsam** [comment]
I've submitted a patch https://github.com/rfc1036/whois/pull/156

**Comment by rfc1036** [comment]
I have implemented a slightly different solution.
