### ISSUE TITLE
Was 5.5.20 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [rfc1036/whois#164]
Homebrew merged a version of 5.5.20 on Thu Nov 9 21:51:53 2023 +0000, but it seems that the tag in the repo was from the 10th of November.  The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do, so I wanted to confirm that this was intentional and nothing malicious is going on.

**Comment by rfc1036** [comment]
I cannot remember what happened two months ago, but I hereby certify that the published tags are accurate.
