### ISSUE TITLE
Network is unreachable for .SE domains

### ISSUE THREAD

**Issue by razerrazer** [rfc1036/whois#166]
Hi,

I need to ask if any of you know whether the "whois" command is still working for .SE domains. I've been using it for years, but a week ago, I encountered an issue when trying to contact domain registrars to find out the owner behind a domain. The IP search still works as usual.

For example:

```
$ whois dn.se
connect: Network is unreachable
```

However, if I use "whois" for a .com domain, it works, but not for the .se domain.

whois --version
Version 5.5.18

**Comment by hubandr** [comment]
they are talking about technical issues on their homepage:

https://internetstiftelsen.se/en/
