### ISSUE TITLE
Enhancing WHOIS Tool Accuracy for Exotic Domains through IANA Server Integration

### ISSUE THREAD

**Issue by brammittendorff** [rfc1036/whois#169]
I've encountered an issue while using the `whois` tool, which generally performs excellently. The problem arises when querying less common or "exotic" domain sections, leading to inconsistent results.

For example, attempting to query the domain for Angola (.ao) using:
```bash
whois bfa.ao
```
results in the message:
```
This TLD has no whois server, but you can access the whois database at
https://www.dns.ao/ao/gca/index.php?id=19
```
This suggests a lack of direct WHOIS server support for certain TLDs within the tool's current configuration, as seen here: [AO WHOIS Server List](https://github.com/rfc1036/whois/blob/ef10478197948b0e43ebb693ae8ae5d98232c155/tld_serv_list#L81C1-L81C63).

However, querying the same domain via the IANA WHOIS server with `netcat` reveals a more comprehensive response, including contact details for the responsible organisation:
```bash
echo "www.bfa.ao" | nc whois.iana.org 43
```
Yielding:
```
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        

domain:       AO

organisation: Ministry of Telecommunications and Information Technologies (MTTI)
address:      Customs street, no. 10
address:      Luanda CP 1459
address:      Angola
etc...
```
This issue is not isolated to the .ao TLD but extends to several others, such as .ad, .al, .aq, .priv.at, .gov.az, .az, .ba, and many more.

Given this context, I recommend reviewing the integration of the `whois.iana.org` server within our tool, especially for TLDs that currently lack direct WHOIS server support. This could potentially offer a more reliable and comprehensive query response for a wider range of domains.

If you're interested in obtaining a comprehensive list of all domains that can be queried using the IANA WHOIS server, please let me know. I'm here to help you access and make the most of this valuable resource for a wider and more inclusive range of domain inquiries.

**Comment by rfc1036** [comment]
You are clearly confusing whois information about the TLD with whois information about the registered SLDs.

`whois ao` returns that same `whois.iana.org` data.

**Comment by brammittendorff** [comment]
You are right my bad.
