### ISSUE TITLE
Could you use a regularily compiled XML whois server list?

### ISSUE THREAD

**Issue by malkusch** [rfc1036/whois#30]
Hi
I maintain https://github.com/whois-server-list/whois-server-list where you can find a XML list containing top level domains from IANA plus its whois servers. I plan to keep that list updated. Feel free to use it.

**Comment by rfc1036** [comment]
Not interested: my own list is better.

**Comment by malkusch** [comment]
Yes, I noticed already that sentence in your readme:

> The internal database is often more accurate than IANA's published one

I am curious how you make that better.

**Comment by rfc1036** [comment]
Hard work and having 15 years of experience at it.

**Comment by malkusch** [comment]
Ok, I hoped a bit more insights so that I could make my list better as well. But thank you anyways.

May I ask you if I can cooperate your list into my? I am not sure about a LICENSE clash, as I am using the WTFL so I guess asking you is the simplest way. Also sorry for putting that question into this non related issue.

**Comment by rfc1036** [comment]
The data contained in the package are databases of facts, so they would be protected by copyright regulations in the UE. Feel free to use them in any way you see fit subject to the published license, the GPL. I see no point in relicensing my work under a different license.

**Comment by malkusch** [comment]
Ok, so I understand you correctly, that when I merge your database into mine I will have to add the GPL to my project as well (regardless of the current WFTL). I asked because I am targeting two further projects as well and I wanted to avoid a huge bulk of different licenses.
