### ISSUE TITLE
Timeout option as in most Linux commands

### ISSUE THREAD

**Issue by szepeviktor** [rfc1036/whois#32]
Good morning!

Please consider implementing timeout option (e.g. as in bind9-host `-W`) that is for the whole operation of your whois client.

We use `whois` in fail2ban alert emails and - as I understand - it could run for up to 60 seconds.
I'd set a 3 seconds timeout.

Thank you!

**Comment by szepeviktor** [comment]
@rfc1036 Could you help me in this?

**Comment by rfc1036** [comment]
I do not think that you made a compelling use case. I would be happy to consider a different timeout value if somebody made some statistics about real world query times: maybe the current 60 seconds timeout is too long, but I am quite sure from my experience that 3 seconds is too short.
If the current timeout is too long for your application then you can easily use timeout(1) to limit it.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
`whois -W 3 ...` would be so much nicer.
