### ISSUE TITLE
.de IDN

### ISSUE THREAD

**Issue by romuald** [rfc1036/whois#33]
*Not sure if this is actually an issue and the job of the whois command*

whois done on ACE (*xn--*) versions for .de domains will always return an *invalid* status because the server expects the encoded version

Example:
```
% whois xn--caf-dma.de
Domain: xn--caf-dma.de
Status: invalid
```

After asking DENIC support, the whois "has" to tell the server it is querying the ACE version:

```
% whois -h whois.nic.de -T st,ace xn--caf-dma.de
Domain: café.de
Domain-Ace: xn--caf-dma.de
Status: connect
```

Would it be possible to add this feature for IDN  .de domains? Or is it outside the scope of the whois command?

**Comment by rfc1036** [comment]
whois already support this if it has been built with IDN support. Did you build it yourself?

**Comment by romuald** [comment]
Yes I have, sorry I guess :)
