### ISSUE TITLE
Windows port

### ISSUE THREAD

**Issue by szepeviktor** [rfc1036/whois#36]
There is an Windows port in alpha:
https://github.com/mfornasa/whois/compare/mfornasa:084b02ceabd82c614d66174876243a8124f4a876...win

Would you welcome a Windows port?

**Comment by rfc1036** [comment]
I will be happy to consider merging a Windows port which does not require a mess of #ifdefs all over the program. I am almost sure that there is a way to use the socket API in Windows without that kind of uglyness.

**Comment by szepeviktor** [comment]
Cc: @mfornasa
