### ISSUE TITLE
Use 'domain *.com' by default instead of '*.com' to subvert spam issues

### ISSUE THREAD

**Issue by squarefractal** [rfc1036/whois#37]
Thanks to whois spamming, the output of whois for many popular domains (especially .com) ends up listing other domains with "google.com" in it:

```
$ whois google.com
(...)
Aborting search 50 records found .....
   Server Name: GOOGLE.COM.AFRI******S.ORG
   Registrar: TUCOWS DOMAINS INC.
   Whois Server: whois.tucows.com
   Referral URL: http://www.tucowsdomains.com

   Server Name: GOOGLE.COM.ANGR******ES.COM
   IP Address: 8.8.8.8
   Registrar: NAME.COM, INC.
   Whois Server: whois.name.com
   Referral URL: http://www.name.com
(...)
```

I'd suggest doing a whois lookup for 'domain (hostname)' for .com domains, instead of the usual '(hostname)' lookup, for the .com domains.

(There are some servers which do not support the `domain` directive, so this can't be used universally.)

**Comment by rfc1036** [comment]
I am trying something like this in 5.2.13.
