### ISSUE TITLE
mkpasswd: explicitly describe in man page that salt is being generated if not given

### ISSUE THREAD

**Issue by makefu** [rfc1036/whois#38]
I had an argument with a collegue that mkpasswd may not generate a salt if none is given.
`--help` explicitly explains this behavior but the manual `mkpasswd(1)` says nothing about this feature.

Because `Incorrect documentation that looks authoritative is worse than no documentation` the man page must contain correct information or should be deleted completely.

Regards

**Comment by rfc1036** [comment]
UN*X passwords have no concept ot "not generating a salt", and anyway which salt is being used is obviously visible in the hashed password.
