### ISSUE TITLE
DENIC_PARAM_CHARSET " -C UTF-8"

### ISSUE THREAD

**Issue by abelbeck** [rfc1036/whois#43]
We cross-compile an embedded Linux speciality distro and choose not to compile ```whois``` with either libidn or libiconv .

In order to query whois.denic.de with 8'bit results such as: "Address: Königsberger Straße" the following patch is needed:
```
--- whois-5.2.13/whois.c.orig	2016-11-08 07:17:26.381230844 -0600
+++ whois-5.2.13/whois.c	2016-11-08 07:46:05.563327605 -0600
@@ -661,7 +661,7 @@
 #ifdef HAVE_ICONV
 # define DENIC_PARAM_CHARSET ""
 #else
-# define DENIC_PARAM_CHARSET " -C US-ASCII"
+# define DENIC_PARAM_CHARSET " -C UTF-8"
 #endif
 
     /* add useful default flags if there are no flags or multiple arguments */
```
And with this patch the ö and ß characters are displayed properly, along with the query results.

At this point in time it would seem no one needs to be prodded to use libiconv (they don't for a special reason), and setting the DENIC_PARAM_CHARSET default to UTF-8 would provide better results for the non-idn/iconv case.

If you don't agree with changing the non-iconv DENIC_PARAM_CHARSET to UTF-8, a compile time option to do so would be appreciated.

Thanks.

**Comment by rfc1036** [comment]
I do not believe that his change is appropriate for a general audience, I favour maintaining backward compatibility.
