### ISSUE TITLE
.TC gTLD has changed their whois server location

### ISSUE THREAD

**Issue by microvb** [rfc1036/whois#47]
Previously, 'whois.adamsnames.tc' was used for whois lookups on the .TC registry.  This has been changed to 'whois.nic.tc' .

Reference :  https://www.iana.org/domains/root/db/tc.html

I understand this was a recent change, however IANA has the date of that record's last update showing as > Record last updated 2014-11-19. Registration date 1997-01-27.

Using the command :

> whois adamsnames.tc

Returns

> getaddrinfo(whois.adamsnames.tc): Name or service not known

**Comment by rfc1036** [comment]
This was fixed in 5.2.13.
