### ISSUE TITLE
whois returning a 1 when query succeeds

### ISSUE THREAD

**Issue by Matty9191** [rfc1036/whois#55]
While debugging an issue with the Python whois module I noticed that whois version 5.2.14 returns a 1 when a query succeeds: 

$ whois prefetch.net 
....
$ echo $?
1

The output from the whois command looks fine so I'm not real clear why the program is returning a 1? I checked the notes from the last two point releases and don't see a fix for this.

**Comment by rfc1036** [comment]
See https://github.com/rfc1036/whois/pull/56 .
