### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by jackschmidt** [rfc1036/whois#80]
Regarding
https://github.com/rfc1036/whois/blob/416b3e9a198fc9d63ab096bb6b6bba6f1250bc09/tld_serv_list#L351-L352
https://github.com/rfc1036/whois/blob/416b3e9a198fc9d63ab096bb6b6bba6f1250bc09/tld_serv_list#L357

Some subdomains are: 

* xn--z5bd4bq1db8d6b.xn--45brj9c
* xn--u5bxfcqewdax4kraj7ob.xn--45brj9c
* xn--e6bg5b.xn--45brj9c

Also written as:
* ডাটামেল্.ভারত
* রবীন্দ্ররচনাবলী.ভারত
* ভার.ভারত

**Comment by rfc1036** [comment]
Fixed in 5.5.4.
