### ISSUE TITLE
License of database files?

### ISSUE THREAD

**Issue by sshine** [rfc1036/whois#82]
Hi @rfc1036,

I'd like to know if the files `new_gtlds_list` and `tld_serv_list` are both released under the GPL 2+ license like `whois.c` is. I'm asking because I'd like to base the Haskell 'whois' library off of these lists, as they seem to be the most comprehensive resource of whois servers available online.

**Comment by rfc1036** [comment]
Yes, they are released with the same license of the code, as much as somebody can claim copyright on a database (this depends on your jurisdiction).
And yes, `tld_serv_list` is the most accurate database of its kind, better than IANA. :-)
