### ISSUE TITLE
Regression in 5.5.4: Hiding text is broken for at., de., cz. domains

### ISSUE THREAD

**Issue by ppisar** [rfc1036/whois#84]
After upgrading from 5.5.3 to 5.5.4, "whois -H nic.at" does not print anything. A similar experience is with de. or cz. domains. This regression was introduced with:

commit caa27b0675e171fe85c043d0199bfe77fddb23b9
Author: Marco d'Itri <md@linux.it>
Date:   Mon Dec 30 03:32:40 2019 +0100

    Fix and update many hiding string

**Comment by FrankSansC** [comment]
Same for .fr, .be, .no, .lu, .ru ...

**Comment by rfc1036** [comment]
Fixed.
