### ISSUE TITLE
Does 'AFILIAS' flag in 'tld_serv_list' cover properly?

### ISSUE THREAD

**Issue by sshine** [rfc1036/whois#86]
In 3a5bcdcc7ed692546b7b8bd16db5fd0fdbafbab5 of 2019-12-31, "whois.afilias-grs.info" is moved from whois.c into make_tld_serv.pl. But exactly one TLD in tld_serv_list, .bz, still uses the `AFILIAS` flag that appears to be the only way to trigger `query_afilias()` (`0x08` in make_tld_serv.pl corresponding to the `case 8:` of `handle_query()` of whois.c).

The commit message of 3a5bcdcc7ed692546b7b8bd16db5fd0fdbafbab5, "Generalize the support for Afilias-style referrals", seems to indicate that the special-casing has to do with handling recursive lookups like "Registrar WHOIS Server" strings that seem to be specifically handled only by `query_afilias()` and `query_crsnic()`.

The remainder of known Afilias TLDs (`ack -i afilias tld_serv_list`) refer to other Afilias servers.

It occurred to me that you can also use "whois2.afilias-grs.net" for .bz:

```haskell
$ whois -h whois.afilias-grs.info nic.bz 2>&1 1>1.txt
$ whois -h whois2.afilias-grs.net nic.bz 2>&1 1>2.txt
$ diff 1.txt 2.txt
20c20
< >>> Last update of WHOIS database: 2020-01-16T17:31:31Z <<<
---
> >>> Last update of WHOIS database: 2020-01-16T17:31:41Z <<<
```

Unless I'm mistaken about this special-casing of .bz (in which all of this is gibberish), is it intentional that this is the only Afilias TLD that receives special handling of `query_afilias()`? In that case, I'm unsure what's generalising about it.

Perhaps it makes sense to mark more Afilias TLDs with the `AFILIAS` flag and not hardcode "whois.afilias-grs.info" anywhere. This is still slightly confusing to the unknowing reader: Why are some TLDs with "afilias" in the server name labelled with `AFILIAS` and others not? Whatever the answer is is deserving of a comment atop `query_afilias()`.

If I've touched on something that can be tidied up, I am happy to provide a pull request.

**Comment by rfc1036** [comment]
TLDs marked this way are the ones with a thin registry model, i.e. which require recursion. Unless you can point me to domains which require recursion in other Afilias-managed TLDs then no changes are needed.

**Comment by rfc1036** [comment]
Closing.
