### ISSUE TITLE
memleak

### ISSUE THREAD

**Issue by lulcat** [rfc1036/whois#92]
Heya, is a memleak in the recursion of handling server or so. The strdup on referral_server needs a free at whois.c line 857 I think:

   referral_server = strdup(p);

I'd leave a patch but I am busy and when I added a free where I thought it should be, it didn't work and ya, guess I can just leave it here though as info. Cheers. 

P.S. attaching a patch which should fix the leak accordingly to debug gremlins.

[m-whois-memleak.patch.txt](https://github.com/rfc1036/whois/files/4798202/m-whois-memleak.patch.txt)

**Comment by lulcat** [comment]
P.S. this should be ok enough I think. 

diff -Naur src/whois/whois.c whois/whois.c
--- src/whois/whois.c	2019-12-31 12:14:30.000000000 +0100
+++ whois/whois.c	2020-06-18 13:22:58.079325346 +0200
@@ -292,8 +292,9 @@
 	server = guess_server(qstring);
 
     ret = handle_query(server, port, qstring, fstring);
-
+		free (fstring);
     exit(ret);
+
 }
 
 /*
@@ -854,7 +855,9 @@
 	if (state == 1 && strneq(buf, "   Registrar WHOIS Server:", 26)) {
 	    for (p = buf; *p != ':'; p++);	/* skip until the colon */
 	    for (p++; *p == ' '; p++);		/* skip the spaces */
-	    referral_server = strdup(p);
+	    char* temp = strdup(p); 
+			referral_server = temp;
+			free (temp);
 	    if ((p = strpbrk(referral_server, "\r\n ")))
 		*p = '\0';
 	    state = 2;

**Comment by rfc1036** [comment]
I know that there are a couple of memory leaks in the program, but it does not really matter since they are tiny and `whois` is not long-lived. I do not mind fixing them as long as this does not make the code more complex.
Your patch is obviously wrong since you `free(3)` `referral_server` and then use it later.
