### ISSUE TITLE
What do I need to do to get whois working in chroot?

### ISSUE THREAD

**Issue by MichaelPehl** [rfc1036/whois#97]
Hello.

I am trying to get whois working in chroot but failed.

Debian 10.8 x64
whois Version 5.4.3.

Error message when chrooted: getaddrinfo(whois.apnic.net): Servname not supported for ai_socktype

Thank you for any hints :)

**Comment by rfc1036** [comment]
Names resolution on your system is not working. This is not a whois-specific problem. Check that you have something sensible in resolv.conf.
